In [23]:
import tensorflow as tf
import numpy as np

In [25]:
#constants
con1= tf.constant(10)
con2= tf.constant(3.14)
con3= tf.constant("this is spartaa")
con4= tf.constant(False)

In [27]:
print([con1,con2,con3,con4])

[<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=float32, numpy=3.14>, <tf.Tensor: shape=(), dtype=string, numpy=b'this is spartaa'>, <tf.Tensor: shape=(), dtype=bool, numpy=False>]


In [29]:
print(con1.numpy())
print(con2.numpy())
print(con3.numpy())
print(con4.numpy())

10
3.14
b'this is spartaa'
False
